version: "3.8"
services:
  redis:
    container_name: promptle-redis
    image: redis:7.0.2
    restart: always
    env_file: .env.dev
    volumes:
      - ./server/redis.conf:/data/redis.conf
    entrypoint: /bin/sh -c
    command: ["redis-server redis.conf --requirepass $$REDIS_PASSWORD"]
  server:
    container_name: promptle-server
    build: "./server"
    depends_on:
      - redis
    ports:
      - ${SERVER_PORT}
    restart: always
    env_file: .env.dev
    environment:
      - NODE_ENV=development
      - SERVER_PORT=${SERVER_PORT}
      - SSL_ENABLED=${SSL_ENABLED}
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - OPEN_AI_SECRET_KEY=${OPEN_AI_SECRET_KEY}
      # - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - ./server:/app
  client:
    container_name: promptle-client
    build: "./client"
    depends_on:
      - server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SERVER_PORT=${SERVER_PORT}
      # - BASE_PATH=${BASE_PATH} # Client should only need BASE_PATH during the react-scripts build step, which doesn't occur in docker
