# TODO: change dumb docker containers to share node_modules maybe
# TODO: add build script
version: "3.8"
services:
  redis:
    container_name: promptle-redis
    image: redis:7.0.2
    # ports: #No need to expose redis
      # - 6379:6379
    restart: always
    volumes:
      - ./server/redis.conf:/data/redis.conf
    command: redis-server redis.conf --requirepass ${REDIS_PASSWORD}
  server:
    container_name: promptle-server
    build: "./server"
    depends_on:
      - redis 
    ports:
      - 5678:5000
    restart: always
    volumes:
      - ./server:/app
      # - /app/node_modules
  client:
    container_name: promptle-client
    build: "./client"
    depends_on:
    - server
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client:/app
      # - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true